### PR TITLE
fix(#5): fix cookie that the very same cookie is sent multiple times …

### LINKED ISSUE #5: Only last cookie gets set when trying to set 2 cookies
I use two cookies for user authentication and authorization in my app. I want to refresh both of them when the user loads a page. I noticed that my `cookie_one` does not get set on page load. Only the second one gets set. Is this a nookies bug (or possibly a bug of the cookie library that nookies uses internally) or am I missing something obvious?

```
static async getInitialProps(ctx: { req; res }) {
      if (parseCookies(ctx).cookie_one && parseCookies(ctx).cookie_two) {
        setCookie(ctx, 'cookie_one', parseCookies(ctx).cookie_one, {
          maxAge: 36000 * 24 * 14,
        });
        setCookie(ctx, 'cookie_two', parseCookies(ctx).cookie_two, {
          maxAge: 36000 * 24 * 14,
        });
      }

      return {};
    }
```

### LINKED ISSUE #15: Overwrite cookie with the same options and name
I am facing an issue, where I call the `setCookie` multiple times in a row on server with same cookie name and options but different values. This might not be a problem because the browser should take the latest which is valid but to be sure I would like to send a cookie only once.

### PR DESCRIPTION
**Pull request by koprivajakub**
…with same options

fix cookie that the very same cookie is sent multiple times with same options

Closes #15

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -46,9 +90,26 @@ export function setCookie(
     if (typeof cookies === 'string') cookies = [cookies]
     if (typeof cookies === 'number') cookies = []
 
-    cookies.push(cookie.serialize(name, value, options))
-
-    ctx.res.setHeader('Set-Cookie', cookies)
+    const parsedCookies = setCookieParser.parse(cookies)
+
+    let cookiesToSet: string[] = []
+    parsedCookies.forEach((parsedCookie: Cookie) => {
```
Comment (maticzav) [inline src/index.ts]: Could we replace this with a more functional code? I was thinking of filtering the cookies instead of pushing and pooling from the list.

File: src/index.ts [hunk 2]
```diff
@@ -1,8 +1,52 @@
...
+}
+
+/**
+ * Create an instance of the Cookie interface
+ *
+ * @param name name of the Cookie
+ * @param value value of the Cookie
+ * @param options Cookie options
+ */
+function createCookie(
```
Comment (maticzav) [inline src/index.ts]: Could you elaborate on the idea behind `createCookie` function? I am not sure I entirely understand why we necessarily need it.

File: src/index.ts [hunk 3]
```diff
@@ -1,8 +1,52 @@
...
 const isBrowser = () => typeof window !== 'undefined'
 
+/**
+ * Compare the cookie and return true if the cookies has equivalent
+ * options and the cookies would be overwritten in the browser storage.
+ *
+ * @param a first Cookie for comparision
+ * @param b second Cookie for comparision
+ */
+function areCookiesEqual(a: Cookie, b: Cookie) {
```
Comment (maticzav) [inline src/index.ts]: I believe the name of this function should be the exact opposite. Am I missing something here?

File: src/index.ts [hunk 4]
```diff
@@ -46,9 +90,26 @@ export function setCookie(
...
-    cookies.push(cookie.serialize(name, value, options))
-
-    ctx.res.setHeader('Set-Cookie', cookies)
+    const parsedCookies = setCookieParser.parse(cookies)
+
+    let cookiesToSet: string[] = []
+    parsedCookies.forEach((parsedCookie: Cookie) => {
+      if (!areCookiesEqual(parsedCookie, createCookie(name, value, options))) {
+        cookiesToSet.push(
+          cookie.serialize(parsedCookie.name, parsedCookie.value, {
```
Comment (maticzav) [inline src/index.ts]: Couldn't we simply pass in `options` here?

File: src/index.ts (hunk 3 above)
Comment (koprivajakub) [reply src/index.ts]: You are right. The function does really the exact opposite. I missed this during a refactoring. Will fix it tomorrow.

File: src/index.ts (hunk 1 above)
Comment (koprivajakub) [reply src/index.ts]: This was a micro optimisation. With filter I need to filter the array first and then serialise all filtered values into the string. So the complexity was O(2n) and this algorithm require only O(n) although it has double memory consumption.

But if you insist I can rewrite it to `parsedCookies.filter().map()` instead

File: src/index.ts (hunk 4 above)
Comment (koprivajakub) [reply src/index.ts]: the `Cookie` interface is not compatible with the `CookieSerializeOptions` interface and the `options` (method argument) is not the same options as the `parsedCookie` options.

File: src/index.ts (hunk 2 above)
Comment (koprivajakub) [reply src/index.ts]: This is just to make the code more clean. The function is not needed at all, but it makes the code below more readable and easier to understand and maintain from my point of view. If you don't want the function here I can move the code directly to the setCookie function.

File: src/index.ts (hunk 1 above)
Comment (maticzav) [reply src/index.ts]: @koprivajakub if you don't mind I would rather have it implemented in `filter` and `map`.

**Comment by maticzav** [comment]
When you compare the two cookies, do you think we should address only the ones with exactly the same properties or "ignore" the defaults in the comparison?

**Comment by koprivajakub** [comment]
> When you compare the two cookies, do you think we should address only the ones with exactly the same properties or "ignore" the defaults in the comparison?

Well I think that the cookie is equivalent in case it will be replaced by the browser. So my point of view is that the cookie consists of 3 parts:

1) unique identifier which is a SET of parameters: `name, domain, path, httpOnly, secured, sameSite`  
2) than it contains a `value` that hold the information which is handed over between server and client and the value can change over time  
3) also it holds an parameter `maxAge` which is just information how long is the `value` valid  

In terms of code like syntax I understand the (1) as a variable name, (2) as variable value and (3) is only parameter of "expiring cache" at what time the variable should be discarded (nulled)

But maybe I do not understand the question?
